### ISSUE TITLE
Toolbar Menu item color 

### ISSUE THREAD

**Issue by Anshul1507** [AshuTyagi16/Instagram-Chat-Theme#1]
Title of menu item in toolbar is black in black toolbar. Causing less readability.

<img src="https://user-images.githubusercontent.com/38963667/99080380-3d3ccd00-25e7-11eb-87ab-2a4b082b6e64.jpeg" height="400" >

**Comment by AshuTyagi16** [comment]
Fixed. Please check latest release.
